export const Strings = {
  logout: 'Logout',
  login: 'Login',
  getStarted: 'Get Started',
  appName: 'Jollyo',
  enterOtp: 'Enter OTP',
  greetingText: 'Hi, Arya!',
  exercises: 'exercises',
  errorInvalidData: 'Error: Invalid data passed to the screen',
  pleaseSelectCorrectShape: 'Please Select a correct shape?',
  goodJob: 'Good Job!',
  unlockedYourNewReward: 'Unlocked Your New Reward',
  congrats: 'Congrats!',
  youUnlockedNewReward: 'You are rewarded with 1 magic reward',
  howMany: 'How many items?',
  canYouChooseTheCorrect: 'Choose the correct animal?',
  chooseKidsInterests: 'Choose kid interests?',
  logout: 'Log out',
  setALimitOnTheScreenTime:
    'Set a limit on the screen time at a stretch to make sure your child watches in moderation',
  manageScreenTime: 'Manage Screen Time',
  drawInside: 'D r a w  I n s i d e',
  childName: 'Child Name',
  yourAge: 'Your age?',
  creatingProfileFor: 'Creating profile for?',
  noRewards: 'No rewards',
  register: 'Register',
  emailType: 'email-address',
  numeric: 'numeric',
  email: 'Email',
  default: 'default',
  password: 'Password',
  dntHaveAnAccount: " Don't have an account? ",
  confirmPassword: 'Confirm Password',
  alreadyHaveAnAccount: 'Already have an account? ',
  exercise: 'Exercise',
  chooseTheCorrectWord: 'Choose the correct word:',
  welcomeAgain: 'Welcome again !',
  welcome: 'Welcome !',
  noAnimalAvailable: 'No Animal Available',
  aLotInteresting: 'A lot interesting features on your\nfavorite topics',
  unlockAll: 'Unlock All',
  premium: 'P r e m i u m',
  yourRewards: 'Y o u r  R e w a r d s',
  pronunciation: 'P r o n u n c i a t i o n s',
  searchMusic: 'Search Music',
  listenTheLatestPoems: 'Listen The Latest Poems',
  noGameAvailable: 'No games available',
  kidsProfileSetting: 'Kids Profile Setting',
  manageYourKidsProfile: 'Manage your kids profile',
  kidActivityStats: 'Kid Activity Stats',
  reviewYourKidGoals: 'Review your kid goals/progress',
  userGuide: 'User Guide',
  goThroughGuideForApp: 'Go through guide for app intro!',
  seeYouSoon: 'See you soon!',
  eraser: 'Eraser',
  resendCode: 'Resend Code',
  youEarnedASticker: 'You earned a sticker:',
  unknownSticker: 'Unknown Sticker',
  totalExercises: 'Total Exercises:',
  age: 'Age: ',
  colors: 'C o l o r s',
  shapes: 'S h a p e s',
  shapesSet: 'Shapes Set',
  numbers: 'N u m b e r s',
  quiz: 'Q u i z',
  animals: 'A n i m a l s',
  alphabets: 'A l p h a b e t s',
  alphabetsSet: 'Alphabets Set',
  twentySixLetter: '26 sets and letters',
  poems: 'P o e m s',
  vehicles: 'V e h i c l e s',
  userGuideHeading: 'U s e r  G u i d e',
  wellDone: 'Well Done! You pronounced correct word !!!!',
  close: 'Close',
};

export const ScreenNames = {
  AuthStack: 'AuthStack',
  BottomStack: 'BottomStack',
  homeNavigator: 'HomeNavigator',
  gameNavigator: 'GameNavigator',
  BoardingScreen: 'onBoardingScreen',
  registerationScreen: 'SignUpScreen',
  loginScreen: 'loginScreen',
  otpScreen: 'OtpScreen',
  profile: 'ProfileScreen',
  interestScreen: 'InterestsScreen',
  homeScreen: 'HomeScreen',
  settingScreen: 'SettingsScreen',
  rewardScreen: 'RewardsScreen',
  gameScreen: 'GamesScreen',
  canvasScreen: 'canvasScreen',
  alphabetsScreen: 'AlphabetsScreen',
  numbersScreen: 'NumericScreen',
  shapesScreen: 'ShapesScreen',
  animalsScreen: 'AnimalsScreen',
  vehicleScreen: 'VehicleScreen',
  kidsGamesScreen: 'KidsGamesScreen',
  colorsScreen: 'ColorsScreen',
  alphabetExerciseMainScreen: 'AlphabetExerciseMainScreen',
  alphabetExerciseScreen: 'AlphabetExerciseScreen',
  numbersExerciseScreen: 'NumbersExerciseScreen',
  shapesExerciseScreen: 'ShapesExerciseScreen',
  animalsExerciseScreen: 'AnimalsExerciseScreen',
  kidsGameExerciseScreen: 'KidsGameExerciseScreen',
  premiumScreen: 'PremiumScreen',
  pronunciationNavigator: 'PronunciationNavigator',
  pronunciation: 'Pronunciation',
  userGuide: 'UserGuide',
  poemsScreen: 'PoemsScreen',
  poemMusicScreen: 'PoemMusicScreen',
};

export const IconNames = {
  playBackOutline: 'play-back-outline',
  playSkipBackOutline: 'play-skip-back-outline',
  pauseOutline: 'pause-outline',
  playOutline: 'play-outline',
  playSkipForwardOutline: 'play-skip-forward-outline',
  playForwardOutline: 'play-forward-outline',
};
