export const Strings = {
  logout: 'Logout',
  login: 'Login',
  getStarted: 'Get Started',
  appName: 'Jollyo',
  enterOtp: 'Enter OTP',
  greetingText: 'Hi, Arya!',
  exercises: 'exercises',
  errorInvalidData: 'Error: Invalid data passed to the screen',
  pleaseSelectCorrectShape: 'Please Select a correct shape?',
  goodJob: 'Good Job!',
  unlockedYourNewReward: 'Unlocked Your New Reward',
  congrats: 'Congrats!',
  youUnlockedNewReward: 'You are rewarded with 1 magic reward',
  howMany: 'How many items?',
  canYouChooseTheCorrect: 'Choose the correct animal?',
  chooseKidsInterests: 'Choose kid interests?',
  logout: 'Log out',
  setALimitOnTheScreenTime:
    'Set a limit on the screen time at a stretch to make sure your child watches in moderation',
  manageScreenTime: 'Manage Screen Time',
  drawInside: 'D r a w  I n s i d e',
  childName: 'Child Name',
  yourAge: 'Your age?',
  creatingProfileFor: 'Creating profile for?',
  noRewards: 'No rewards',
  register: 'Register',
  emailType: 'email-address',
  numeric: 'numeric',
  email: 'Email',
  default: 'default',
  password: 'Password',
  dntHaveAnAccount: " Don't have an account? ",
  confirmPassword: 'Confirm Password',
  alreadyHaveAnAccount: 'Already have an account? ',
  exercise: 'Exercise',
  chooseTheCorrectWord: 'Choose the correct word:',
  welcomeAgain: 'Welcome again !',
  noAnimalAvailable: 'No Animal Available',
  aLotInteresting: 'A lot interesting features on your\nfavorite topics',
  unlockAll: 'Unlock All',
  premium: 'P r e m i u m',
  yourRewards: 'Y o u r  R e w a r d s',
  pronunciation: 'P r o n u n c i a t i o n s',
  searchMusic: 'Search Music',
  listenTheLatestPoems: 'Listen The Latest Poems',
};

export const ScreenNames = {
  AuthStack: 'AuthStack',
  BottomStack: 'BottomStack',
  homeNavigator: 'HomeNavigator',
  gameNavigator: 'GameNavigator',
  BoardingScreen: 'onBoardingScreen',
  registerationScreen: 'SignUpScreen',
  loginScreen: 'loginScreen',
  otpScreen: 'OtpScreen',
  profile: 'ProfileScreen',
  interestScreen: 'InterestsScreen',
  homeScreen: 'HomeScreen',
  settingScreen: 'SettingsScreen',
  rewardScreen: 'RewardsScreen',
  gameScreen: 'GamesScreen',
  canvasScreen: 'canvasScreen',
  alphabetsScreen: 'AlphabetsScreen',
  numbersScreen: 'NumericScreen',
  shapesScreen: 'ShapesScreen',
  animalsScreen: 'AnimalsScreen',
  vehicleScreen: 'VehicleScreen',
  kidsGamesScreen: 'KidsGamesScreen',
  colorsScreen: 'ColorsScreen',
  alphabetExerciseMainScreen: 'AlphabetExerciseMainScreen',
  alphabetExerciseScreen: 'AlphabetExerciseScreen',
  numbersExerciseScreen: 'NumbersExerciseScreen',
  shapesExerciseScreen: 'ShapesExerciseScreen',
  animalsExerciseScreen: 'AnimalsExerciseScreen',
  kidsGameExerciseScreen: 'KidsGameExerciseScreen',
  premiumScreen: 'PremiumScreen',
  pronunciationNavigator: 'PronunciationNavigator',
  pronunciation: 'Pronunciation',
  userGuide: 'UserGuide',
  poemsScreen: 'PoemsScreen',
};
