import {images} from '../assets/images';

export const Strings = {
  logout: 'Logout',
  login: 'Login',
  getStarted: 'Get Started',
  appName: 'Jollyo',
  enterOtp: 'Enter OTP',
  greetingText: 'Hi, Arya!',
  exercises: 'exercises',
  errorInvalidData: 'Error: Invalid data passed to the screen',
  pleaseSelectCorrectShape: 'Please Select a correct shape?',
  goodJob: 'Good Job!',
  unlockedYourNewReward: 'Unlocked Your New Reward',
  congrats: 'Congrats!',
  youUnlockedNewReward: 'You are rewarded with 1 magic reward',
  howMany: 'How many items?',
  canYouChooseTheCorrect: 'Choose the correct animal?',
  chooseKidsInterests: 'Choose kid interests?',
  logout: 'Log out',
  setALimitOnTheScreenTime:
    'Set a limit on the screen time at a stretch to make sure your child watches in moderation',
  manageScreenTime: 'Manage Screen Time',
  drawInside: 'Draw Inside',
  childName: 'Child Name',
  yourAge: 'Your age?',
  creatingProfileFor: 'Creating profile for?',
  noRewards: 'No rewards',
  register: 'Register',
  emailType: 'email-address',
  numeric: 'numeric',
  email: 'Email',
  default: 'default',
  password: 'Password',
  dntHaveAnAccount: " Don't have an account? ",
  confirmPassword: 'Confirm Password',
  alreadyHaveAnAccount: 'Already have an account? ',
  // confirmPassword: 'Confirm Password',
  // signUp: 'Sign Up',
  // name: 'Name',
  // phoneNumber: 'Phone Number',
};

export const ScreenNames = {
  AuthStack: 'AuthStack',
  BottomStack: 'BottomStack',
  homeNavigator: 'HomeNavigator',
  gameNavigator: 'GameNavigator',
  BoardingScreen: 'onBoardingScreen',
  registerationScreen: 'SignUpScreen',
  loginScreen: 'loginScreen',
  otpScreen: 'OtpScreen',
  profile: 'ProfileScreen',
  interestScreen: 'InterestsScreen',
  homeScreen: 'HomeScreen',
  settingScreen: 'SettingsScreen',
  rewardScreen: 'RewardsScreen',
  gameScreen: 'GamesScreen',
  listScreen: 'ListsScreen',
  alphabetsScreen: 'AlphabetsScreen',
  numbersScreen: 'NumericScreen',
  shapesScreen: 'ShapesScreen',
  animalsScreen: 'AnimalsScreen',
  vehicleScreen: 'VehicleScreen',
  kidsGamesScreen: 'KidsGamesScreen',
  colorsScreen: 'ColorsScreen',
  alphabetExerciseMainScreen: 'AlphabetExerciseMainScreen',

  alphabetExerciseScreen: 'AlphabetExerciseScreen',
  numbersExerciseScreen: 'NumbersExerciseScreen',
  shapesExerciseScreen: 'ShapesExerciseScreen',
  animalsExerciseScreen: 'AnimalsExerciseScreen',
  kidsGameExerciseScreen: 'KidsGameExerciseScreen',
  //   alphabetExerciseScreen:'AlphabetExerciseScreen'
  //   alphabetExerciseScreen:'AlphabetExerciseScreen'
  //   alphabetExerciseScreen:'AlphabetExerciseScreen'
};

export const InterestsData = [
  {title: 'Alphabets', imageSource: images.alphabets.a},
  {title: 'Numbers', imageSource: images.numbers.one},
  {title: 'Maths', imageSource: images.operations.multiply},
  {title: 'Shapes', imageSource: images.shapes.circle},
  {title: 'Animals', imageSource: images.animals.cat},
  {title: 'Games', imageSource: images.games.captainAmerica},
];
